### ISSUE TITLE
Invert `plot_er_distributions` y-axis?

### ISSUE THREAD

**Issue by aghaynes** [snsf-data/ERforResearch#3]
Nice package... :)

Just a suggestion... for the `plot_er_distributions` figure, it might make sense to invert the y-axis so that rank 1 is highest... makes more sense from the interpretational perspective... similar to a ranking table where 1st rank is at the top...

Feel free to ignore :)

**Comment by rachelHey** [comment]
Sorry for the very late reply. 
First of all, thank you for the interest. This request is actually easily done as  `plot_er_distributions` uses ggplot2. Simply add a `scale_y_reverse()` as such (from the example code): 

```
library(ERforResearch)
data_panel1 <- get_mock_data() %>%
  filter(panel == "p1")
mcmc_samples <- get_mcmc_samples(data = data_panel1,
                                 id_application = "application",
                                 id_voter = "voter",
                                 grade_variable = "num_grade")
p <- plot_er_distributions(mcmc_samples,
                           n_proposals = data_panel1 %>%
                             summarise(n = n_distinct(application)) %>%
                             pull(),
                           number_fundable = 5)
# You get what you want using the following: 
p + scale_y_reverse()
```
